name: Build and Sign

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        
    - name: Build Package
      run: dotnet pack --configuration Release src/AClassLibrary/AClassLibrary.csproj
      
    - name: Upload signing file list
      uses: actions/upload-artifact@v3
      with:
        name: config
        path: config
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: BuildArtifacts
        path: src/AClassLibrary/bin/Release/**/*.nupkg   
    
  sign:
    permissions:
      id-token: write # Required for requesting the JWT
      
    runs-on: windows-latest
    steps:
    
    - name: Download signing config
      uses: actions/download-artifact@v3
      with:
        name: config
        
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: BuildArtifacts
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        
    - name: Install Sign CLI tool
      run: dotnet tool install --tool-path . sign --version 0.9.0-beta.23063.3
      
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        allow-no-subscriptions: true
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

